Repository AGH-Wstep-do-Informatyki-2023-2024/HSKP, pull requests merged in 2024-01, with the labels that each got.

#5 Board, snake, fruit
  projekt/snake_h
  projekt/snake_head.png
Labels: help wanted, question

#6 Update snake_h
  projekt/snake_h
Labels: help wanted, question

#9 Game over functionality
  projekt/snake_h
  projekt/snake_head copy.png
  snake_head.png
Labels: enhancement, help wanted, question

#11 Piotrek
  projekt/Happiness Mood Demo.ttf
  projekt/snake_h
Labels: documentation, enhancement
